apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
spec:
  containers:
  - name: busybox
    image: appropriate/curl
    command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
