apiVersion: v1
kind: Service
metadata:
 name: todoapp-clusterip-service
 namespace: todoapp
spec:
 type: ClusterIP
 selector:
   app: todolist
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
