apiVersion: v1
kind: Service
metadata:
  name: todoappclusterip
  namespace: todoapp
spec:
  selector:
    app: todoapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
