apiVersion: v1
kind: Service
metadata:
  name: todoapp-clusterip-service
  namespace: todoapp
spec:
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
