apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: todoapp
spec:
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
