apiVersion: v1
kind: Service
metadata:
  name: todoapp-clusterip-service
  namespace: todoapp
spec:
  selector:
    app: todolist
  type: ClusterIP
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
