apiVersion: v1
kind: Service
metadata:
  name: todo-nodeport-service
  namespace: todoapp
spec:
  selector:
    app: todoapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
