apiVersion: v1
kind: Service
metadata:
  name: todolist-nodeport
spec:
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort
