apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport
  namespace: todoapp
spec:
  selector:
    app: todolist
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
