apiVersion: v1
kind: Pod
metadata:
  name: todoapppod1
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 40
      periodSeconds: 10

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapppod2
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 40
      periodSeconds: 10
