apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: salaxambar/todoapp:3.0.0
    ports:
    - containerPort: 8080
    env:
    - name: DATABASE_NAME
      value: "your_database_name"
    - name: DATABASE_USER
      value: "your_database_user"
    - name: DATABASE_PASSWORD
      value: "your_database_password"
    - name: DATABASE_HOST
      value: "your_database_host"
    - name: DATABASE_PORT
      value: "your_database_port"
    - name: DJANGO_SECRET_KEY
      value: "your_secret_key"
    - name: ALLOWED_HOSTS
      value: "localhost,127.0.0.1"
    - name: DEBUG
      value: "True"
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: salaxambar/todoapp:3.0.0
    ports:
    - containerPort: 8080
    env:
    - name: DATABASE_NAME
      value: "your_database_name"
    - name: DATABASE_USER
      value: "your_database_user"
    - name: DATABASE_PASSWORD
      value: "your_database_password"
    - name: DATABASE_HOST
      value: "your_database_host"
    - name: DATABASE_PORT
      value: "your_database_port"
    - name: DJANGO_SECRET_KEY
      value: "your_secret_key"
    - name: ALLOWED_HOSTS
      value: "localhost,127.0.0.1"
    - name: DEBUG
      value: "True"
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5


