apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: rozdorozhnii/todoapp:3.1.0
    imagePullPolicy: Always
    env:
      - name: SECRET_KEY
        value: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: rozdorozhnii/todoapp:3.1.0
    imagePullPolicy: Always
    env:
      - name: SECRET_KEY
        value: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
