apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: kagerou4649/todoapp:3.1.0
    ports:
    - containerPort: 8080
    env:
    name: EXTERNAL_ENDPOINT
    value: http://todoapp-clusterip.todoapp.svc.cluster.local
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/readiness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: kagerou4649/todoapp:3.1.0
    ports:
    - containerPort: 8080
    env:
    name: EXTERNAL_ENDPOINT
    value: http://todoapp-clusterip.todoapp.svc.cluster.local
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/readiness
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
