apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
