apiVersion: v1
kind: Pod
metadata:
  name: todoapp-0
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: abnormaltype/todoapp:3.0.0
    env:
    - name: EXTERNAL_ENDPOINT
      value: http://todoapp-clusterip.todoapp.svc.cluster.local
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/healthz
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: abnormaltype/todoapp:3.0.0
    env:
    - name: EXTERNAL_ENDPOINT
      value: http://todoapp-clusterip.todoapp.svc.cluster.local
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: api/healthz
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
