apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
    - name: todoapp
      image: fredfredburger/todoapp:3.0.2
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: api/health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: api/ready
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
    - name: todoapp
      image: fredfredburger/todoapp:3.0.2
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: api/health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: api/ready
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
