apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    ports:
    - containerPort: 8080
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: DJANGO_SETTINGS_MODULE
      value: myproject.settings
    - name: DATABASE_URL
      value: postgres://user:password@host:5432/mydb
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp
    image: ikulyk404/todoapp:3.0.0
    ports:
    - containerPort: 8080
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: DJANGO_SETTINGS_MODULE
      value: myproject.settings
    - name: DATABASE_URL
      value: postgres://user:password@host:5432/mydb
    livenessProbe:
      httpGet:
        path: api/health
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: api/ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5


